# Generated by Django 5.2 on 2025-04-09 18:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Account',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('archived', models.BooleanField(default=False)),
                ('font_color_hex', models.CharField(help_text='Hex color code for font display (e.g., #000000)', max_length=7)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
            },
        ),
        migrations.CreateModel(
            name='Bill_Status',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('archived', models.BooleanField(default=False)),
                ('highlight_color_hex', models.CharField(help_text='Hex color code for highlighting (e.g., #FFFFFF)', max_length=7)),
            ],
            options={
                'verbose_name': 'Bill Status',
                'verbose_name_plural': 'Bill Statuses',
            },
        ),
        migrations.CreateModel(
            name='Bank_Account_Instance',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('priority', models.IntegerField(default=0, help_text='Priority for sorting/display')),
                ('due_date', models.DateField(help_text='Date this instance is scheduled for or occurred on')),
                ('pay_date', models.DateField(blank=True, help_text='Actual date this instance was actioned/paid', null=True)),
                ('name', models.CharField(help_text="Description (e.g., 'Transfer to Savings', 'Payday Deposit')", max_length=100)),
                ('archived', models.BooleanField(default=False)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Amount related to this instance (e.g., transfer amount). Or balance snapshot on due_date.', max_digits=10, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='api.bank_account')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_account_instances', to='api.bill_status')),
            ],
            options={
                'verbose_name': 'Bank Account Instance/Transaction',
                'verbose_name_plural': 'Bank Account Instances/Transactions',
                'ordering': ['due_date', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('default_amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('default_draft_account', models.ForeignKey(blank=True, help_text='Default account this bill is usually paid from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_bills', to='api.bank_account')),
            ],
            options={
                'verbose_name': 'Bill Definition',
                'verbose_name_plural': 'Bill Definitions',
            },
        ),
        migrations.CreateModel(
            name='Due_Bills',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('priority', models.IntegerField(default=0, help_text='Priority for sorting/display (e.g., 0=Normal, 1=High)', validators=[django.core.validators.MinValueValidator(0)])),
                ('due_date', models.DateField()),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('min_amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('archived', models.BooleanField(default=False)),
                ('confirmation', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_instances', to='api.bills')),
                ('draft_account', models.ForeignKey(blank=True, help_text='Account the payment was/will be drafted from for this specific instance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='due_bills_drafts', to='api.bank_account')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='due_bills', to='api.bill_status')),
            ],
            options={
                'verbose_name': 'Due Bill / Bill Instance',
                'verbose_name_plural': 'Due Bills / Bill Instances',
                'ordering': ['due_date', 'priority'],
            },
        ),
    ]
