# Generated by Django 5.2 on 2025-04-09 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurrence',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('calculation', models.CharField(blank=True, help_text="Optional: Description or parameters for calculation (e.g., 'Every 1st', 'Bi-Weekly', JSON/Cron string)", max_length=100)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Recurrence Pattern',
                'verbose_name_plural': 'Recurrence Patterns',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bank_account_instance',
            name='recurrence',
            field=models.ForeignKey(blank=True, help_text='The recurrence pattern associated with this instance, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_account_instances', to='api.recurrence'),
        ),
        migrations.AddField(
            model_name='due_bills',
            name='recurrence',
            field=models.ForeignKey(blank=True, help_text='The recurrence pattern associated with this bill instance, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='due_bills', to='api.recurrence'),
        ),
    ]
